# Generated by Django 4.0.6 on 2022-07-15 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employeedetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(default='vector', on_delete=django.db.models.deletion.DO_NOTHING, to='Employeedetails.department', verbose_name='Department'),
        ),
    ]
